### ISSUE TITLE
Implement "gi edit"

### ISSUE THREAD

**Issue by rinswind** [dspinellis/git-issue#17]
Should work like "gi new", but load the issue file

**Comment by dspinellis** [comment]
Sounds like a worthwhile addition.  Would you like to implement and document it?

**Comment by tekknolagi** [comment]
Is it expected that this would change the sha of the issue? Or would it keep the sha and make changes in the issues repo?

**Comment by dspinellis** [comment]
The issue's identifier is its number (as is a branch's name), not its SHA.  So yes the SHA can change.

**Comment by tekknolagi** [comment]
When you say "its number", do you mean, for example, the first line of this output?

```
issue c1cdc6b920e9065d885398f7f96db80847dbe3f9
Author: Maxwell Bernstein <tekknolagi@gmail.com>
Date:   Tue, 5 Jun 2018 16:04:52 -0700
Tags:   open

    Test issue
```

**Comment by dspinellis** [comment]
I was under the impression that we also stored sequence numbers.  Apparently we don't.  For GitHub issues integration #27  we'll need that.  This also solves the editing problem.

**Comment by aronisstav** [comment]
@dspinellis Perhaps this can be closed now. (Also, happy 100 commits 🎉 )
