### ISSUE TITLE
Mention SD in Related work

### ISSUE THREAD

**Issue by lbragaglia** [dspinellis/git-issue#34]
In README/Related work, please consider adding a reference to [SD (Simple Defects)](http://syncwith.us/sd/), a (now defunct?) distributed bug tracking system based on a distributed db and able to import/export from/to foreign ticketing systems.

See this old LWN article [Distributed bug tracking](https://lwn.net/Articles/281849/) for other historical references.

**Comment by aronisstav** [comment]
Could open another issue, but I'd rather comment on this one with a similar case.

I recently came across "SIT Issue Tracking", which is a module for SIT (see below) and can be summarized as (from their [README.md](https://github.com/sit-fyi/issue-tracking/blob/master/README.md)):

> [SIT Issue Tracking](https://github.com/sit-fyi/issue-tracking) is a compact tool to track and share project issues in and between decentralized teams. Its goal is to lower the barrier for having an independently operated, shared issue tracker.

It is based on SIT, which can be summarized as (from their [README.md](https://github.com/sit-fyi/sit/blob/master/README.md)):

> [SIT](https://sit.fyi/) is a compact tool that helps tracking and sharing information between people and systems in a decentralized, sporadically-online environment (aka "the real world").
