### ISSUE TITLE
Support issue attachments

### ISSUE THREAD

**Issue by dspinellis** [dspinellis/git-issue#36]
Can use the same mechanism as comments, ideally with common elements refactored to utility routines.

**Comment by dspinellis** [comment]
Implemented by @vyrondrosos as part of GSoC 2019.

**Comment by Jonathan-79** [comment]
Hi. I'm a little confused. This issue says that "issue attachments" was implemented by @vyrondrosos as part of GSoC 2019, but looking at the source code, it appears that it is not implemented yet:

 https://github.com/dspinellis/git-issue/blob/a28148910bee3d9b506ef88d96591362a38f50eb/git-issue.sh#L1473-L1476


Is this feature implemented?

**Comment by dspinellis** [comment]
Hi @vyrondrosos, do you remember the story here?
