### ISSUE TITLE
Assignee should be included in search within sub_list function

### ISSUE THREAD

**Issue by vishnu350** [dspinellis/git-issue#39]
In line 882 of git-issue.sh (for the sub_list function):
`  find issues -type f -name tags -o -name milestone |`

It should also include assignee:
`  find issues -type f -name tags -o -name assignee -o -name milestone |`

This will help assignees track their own tasks.

**Comment by dspinellis** [comment]
Thank you for the idea!  The `find` command only provides a list of all issues.  Adding `assignee` won't change its results in the way you suggest.

**Comment by vishnu350** [comment]
Actually, the method I suggested worked for me on my local model. It gives a list of tickets that were only assigned to the assignee, and it is kinda useful to our small group. Eg: git-issue list Vishnu

**Comment by dspinellis** [comment]
Ah, OK, I see.  That's a good idea.  Let me think how it should be best implemented and specified.

**Comment by dspinellis** [comment]
I am moving this requirement to issue #37.
