### ISSUE TITLE
If I rewrite history, so SHA hashes change, can this break issues and comments?

### ISSUE THREAD

**Issue by kajmagnus** [dspinellis/git-issue#50]
Hi, from the docs:

>Each issue is stored in a directory named issues/xx/xxxxxxx..., where the x's are the SHA of the issue's initial commit.
>...
>A comments directory where comments are stored, each with the SHA of a commit containing the text gi comment mark issue SHA.

This makes me wonder what'll happen if:

1) Mallory creates a meaningless issue with weird unpolite text, including someone else's copyrighted all-rights-reserved file, and a 20 MB file.
2) Alice creates a friendly and helpful issue.
3) Bob posts useful comments in Alice's issue.
4) I find Mallory's angry weird issue, and rewrite the Git history to delete it, and also to remove the all-rights-reserved copyrighted file and the 20 MB too-large file from the Git history.

Now, what has happened with Alice's issue and Bob's comments? They are based on SHA hashes, but all hashes have now changed. Is Alice's issue + Bob's comments now broken maybe?

**Comment by dspinellis** [comment]
The SHA identifying the issue is used in order to get a globally unique identifier.  I think the repo after the change you describe is likely to work, but it depends how Git will apply subsequent changes.  Can you please try it out ad report back?  What if we change the identifying SHA to a UUID?

**Comment by kajmagnus** [comment]
Hi @dspinellis  thanks for the reply. Sorry I never had time to try out what'd happen.
