### ISSUE TITLE
Document jq as a requirement in README.md

### ISSUE THREAD

**Issue by vyrondrosos** [dspinellis/git-issue#52]
It seems that git-issue has software requirements, that are not standard in all distributions. An example I found on my system, was `jq` while running test.sh. It would be nice if that sort of thing was documented in README.md and/or checked for in the `Makefile`. Maybe it should be optional, since it's only used during testing?

**Comment by dspinellis** [comment]
Good point!  Even better, skip tests requiring jq if it's missing.  Want to submit a PR?

**Comment by vyrondrosos** [comment]
Sounds good. Are there any other non-trivial requirements I should include checks for?

**Comment by vyrondrosos** [comment]
Upon further review, it seems `jq` is not only used during testing, but also in `git-issue.sh` to parse data from the Github API. Since there is already a check for it in `test.sh`, it doesn't seem appropriate to duplicate the test in `Makefile`. 

As such, I'll submit a PR only adding it in a Requirements section.(and fixing a typo I stumbled upon in `git-issue.sh`.)

**Comment by dspinellis** [comment]
True.  The main program also has checks for *jq* and *curl*.
