### ISSUE TITLE
Question: why is an issue distributed over so many files?

### ISSUE THREAD

**Issue by rdmueller** [dspinellis/git-issue#59]
great concept. 
What is the rationale / design decision behind splitting an issue over so many files?
I hoped for one file per issue to make it easier to modify them manually...

**Comment by dspinellis** [comment]
There are pros and cons for each direction.  Separating attributes to different files makes it easier to search for a value of a specific attribute (e.g. tag).  Typically you want to modify only a single attribute, so it's not much of a problem. I could have used [GNU Recutils](https://www.gnu.org/software/recutils/), but this would have introduced another dependency.
