### ISSUE TITLE
git issue import from gitlab only imports 20 issues

### ISSUE THREAD

**Issue by mjyc** [dspinellis/git-issue#72]
### The Problem

`git issue import {username} {reponame}` only imports first 20 issues because the gitlab api returns only 20 issues (see https://docs.gitlab.com/ee/api/issues.html#issues-pagination).

### The Expected Behavior

`git issue import {username} {reponame}` should import all issues.

### Potential Directions for Solution

- use [pagination info in header](https://docs.gitlab.com/ee/api/README.html#other-pagination-headers) to iterate through pages?

**Comment by vyrondrosos** [comment]
`git-issue` does attempt to use pagination for both GitHub and GitLab (through the `rest_next_page_url()` function). From my tests, it seems that the regex that matches the next page didn't match the links that GitLab returns. I've made a pull request that fixes the issue for me.
