### ISSUE TITLE
im giving errors

### ISSUE THREAD

**Issue by delokman** [dspinellis/git-issue#83]
<pre>hint: See the &apos;Note about fast-forwards&apos; in &apos;git push --help&apos; for details.
<font color="#8AE234"><b>server@server-System</b></font>:<font color="#729FCF"><b>~/Desktop/pok/scrum-issue</b></font>$ ^C
<font color="#8AE234"><b>server@server-System</b></font>:<font color="#729FCF"><b>~/Desktop/pok/scrum-issue</b></font>$ clear

<font color="#8AE234"><b>server@server-System</b></font>:<font color="#729FCF"><b>~/Desktop/pok/scrum-issue</b></font>$ git issue init # Initialize issue repository
An .issues directory is already present
<font color="#8AE234"><b>server@server-System</b></font>:<font color="#729FCF"><b>~/Desktop/pok/scrum-issue</b></font>$ git issue list # List open issues
7130fde New issue entered from the command line
<font color="#8AE234"><b>server@server-System</b></font>:<font color="#729FCF"><b>~/Desktop/pok/scrum-issue</b></font>$ git issue git remote add origin git@gitlab.com:livetrader/scrum-issue.git
fatal: remote origin already exists.
<font color="#8AE234"><b>server@server-System</b></font>:<font color="#729FCF"><b>~/Desktop/pok/scrum-issue</b></font>$ git issue git push -u origin master
To gitlab.com:livetrader/scrum-issue.git
 ! [rejected]        master -&gt; master (non-fast-forward)
error: failed to push some refs to &apos;git@gitlab.com:livetrader/scrum-issue.git&apos;
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: &apos;git pull ...&apos;) before pushing again.
hint: See the &apos;Note about fast-forwards&apos; in &apos;git push --help&apos; for details.
<font color="#8AE234"><b>server@server-System</b></font>:<font color="#729FCF"><b>~/Desktop/pok/scrum-issue</b></font>$ 

</pre>

**Comment by dspinellis** [comment]
It seems you have diverged from the remote repo. You can either clone it again or `git push -f` to it.
