### ISSUE TITLE
macos: fails when import issues without comments

### ISSUE THREAD

**Issue by zxcat** [dspinellis/git-issue#98]
Error message: `fatal: invalid date format: null`.

Some debug showed the problem.
macos `seq`:
```sh
$ seq 0 -1
0
-1
```

GNU `seq`:
```sh
$ gseq 0 -1
# nothing
```

"Fixed" this bug by changing `seq` to `gseq` here: https://github.com/dspinellis/git-issue/blob/28a61e8db94e3bb79fdffdfed474e508d5380f62/lib/git-issue/import-export.sh#L576

**Comment by dspinellis** [comment]
Thank you!  I'm trying to think of a portable fix.

**Comment by zxcat** [comment]
Something like:
https://github.com/dspinellis/git-issue/blob/28a61e8db94e3bb79fdffdfed474e508d5380f62/git-issue.sh#L53-L57
should do the trick

**Comment by dspinellis** [comment]
Thanks!  But is `gseq` available on macOS by default or did you install it?  I see it's not available on my macOS 12.5.1 nor on FreeBSD.

**Comment by zxcat** [comment]
`gseq` installed by brew coreutils, which is already required for `gdate`

**Comment by stasinos** [comment]
GNU seq can be gotten rid of by using the range() command in jq. Please consider my PR.
